### ISSUE TITLE
Kick-off Go auto-instrumentation group

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-go-instrumentation#1]
There have been two donation proposals for different forms of auto-instrumentation:

https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/2 @edeNFed 
https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/3 @pdelewski 

There is also an ongoing effort to build community support for the "Launcher" concept, a simplified way to start OTel SDKs via configuration and environment variables. @JamieDanielson @robbkidd @kentquirk @MikeGoldsmith 

I have seeded the maintainers of this repository using @MadVikingGod @MrAlias @Aneurysm9 and myself. The goal is to build new maintainers and owners for this group eventually. Existing @open-telemetry/go-approvers and @open-telemetry/go-triagers are welcome but have not been added to this repo.

My goal in bringing all of these groups together is that we begin to standardize on the ways that users will configure SDKs and auto-instrumentation via packages in this repository. As I mentioned in https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/2, I think it would be great to see collaboration with the Go team in this area, too.

Please discuss, and thanks for the interest.

**Comment by MrAlias** [comment]
I would like to propose we have a kick off meeting. I'm currently AFK, but can post a doodle poll to determine the best time (or if someone else feels inclined, feel free to and one). I am thinking sometime next week if that works for everyone?

**Comment by Aneurysm9** [comment]
I'll be traveling next week, so anything other than Friday might be hard for me to make, but +1 to a poll for times.

**Comment by MrAlias** [comment]
> I'll be traveling next week, so anything other than Friday might be hard for me to make, but +1 to a poll for times.

I'll include next Friday in the poll, and dates the week after instead.

**Comment by MrAlias** [comment]
[Here](https://doodle.com/meeting/participate/id/dGZ3pB8b) is a doodle poll link. If you would like to participate in the kick-off meeting, please respond to that poll by next Wednesday (2022-08-10) 5pm Pacific time. I will create a meeting for the kick-off on the OTel calendar based on the responses then.

cc @MadVikingGod @Aneurysm9 @JamieDanielson @robbkidd @kentquirk @MikeGoldsmith @edeNFed @pdelewski @jmacd @open-telemetry/go-approvers @open-telemetry/go-triagers

**Comment by pdelewski** [comment]
This week I started 2 weeks vacation, so for me week starting 15.08 would work best

**Comment by MrAlias** [comment]
I was not able to find a time that worked for everyone with the last doodle poll. I will put another one together and post it here in a bit.

**Comment by edeNFed** [comment]
Any updates? I'll be happy to help in scheduling the meeting if needed.

**Comment by MrAlias** [comment]
It looks like Tuesday September 6th 9:30am-10:30am (Pacific time) is the most available time. I'll add a meeting to the OTel calendar for then.

@pdelewski you had listed this as "if need be". I'm hoping to have @dashpole there otherwise I would have gone with Monday morning. Are you okay with this?

**Comment by pdelewski** [comment]
@MrAlias I'm ok with this and will join. I listed this as "if need be" due to other activity at that time.

**Comment by MrAlias** [comment]
Kick-off meeting agenda:

1. (Tyler) Administrative:
   1. When should we have SIG meetings?
      1. Bi-weekley
      1. Next meeting the 20th of Sep.
   2. Repository name, opentelemetry-go-instrumentation, is this okay for all?
      1. This is from OTel precedent
   3. Teams: maintainers and approvers.
2. (Tyler) Project readme needed
3. (Tyler) Missing [issues](https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues)?
4. (Eden) What this SIG is going to work on? (copied from jmacd’s technical committee response to the donations)
   1. [Runtime automatic instrumentation](https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/2)
   2. [Compile time automatic instrumentation](https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/3)
   3. Automatic Go OpenTelemetry SDK configuration
   4. Better integration between Go built-in diagnostic features (like pprof) and OpenTelemetry SDK
   5. (Runtime metrics: To be discussed in this week’s Go SIG. -jmacd)

Kick-off meeting notes

- The runtime eBPF filter and compile time code annotation are complimentary.
- We have two main project: eBPF, and compile annotation
  - We need 3+ people to work on a project all from different companies
- Next SIG meeting:
  - Demo both approaches
  - Get a limitation of both approaches
  - Get an understanding of the benefits of both
- We should consider the “auto” configuration of the SDK out of the initial scope of this project.
- We need to communicate what is being done on user behalf so they know about legal implications about licensing.
