### ISSUE TITLE
Consolidate HTTP probes

### ISSUE THREAD

**Issue by MikeGoldsmith** [open-telemetry/opentelemetry-go-instrumentation#101]
Currently we have two HTTP based probes (net/http and gorilla) and a third to be added in #100. The probes are almost identical apart from the registration name and could be unified. The instrumentors would then deploy the unified probe instead of a custom version. Each probe is based on the net/http `ServeHTTP(w ResponseWriter, r *Request)` interface.

This would make probe maintenance easier by reducing code and would allow improvements to be applied generically instead. eg HTTP response parsing.

TODOs
- [ ] Ensure consts are used for max loop iterations - suggestion from @pdelewski in #92 [comment](https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/92#discussion_r1189869888)
- [ ] Ensure we use constants where possible for indexing - suggestion from @pdelewski [comment](https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/91#discussion_r1226528258)

**Comment by MrAlias** [comment]
This appears resolved. We currently only have one probe for HTTP (counting the client/server probes as one). Closing.
