### ISSUE TITLE
Init Pod - Intrumentation Crashed

### ISSUE THREAD

**Issue by baole229801** [open-telemetry/opentelemetry-go-instrumentation#1079]
I have followed all the instructions, but when running the pod, it crashed. This is the error.

{"level":"error","ts":1725947775.8350706,"logger":"Instrumentation.Manager","caller":"instrumentation/manager.go:200","msg":"error while loading probes, cleaning up","name":"net/http/client","error":"invalid offset for the field in version: net/url.URL:OmitHost (1.18.0)","stacktrace":"go.opentelemetry.io/auto/internal/pkg/instrumentation.(*Manager).load\n\t/app/internal/pkg/instrumentation/manager.go:200\ngo.opentelemetry.io/auto/internal/pkg/instrumentation.(*Manager).Run\n\t/app/internal/pkg/instrumentation/manager.go:143\ngo.opentelemetry.io/auto.(*Instrumentation).Run\n\t/app/instrumentation.go:162\nmain.main\n\t/app/cli/main.go:120\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:271"}
{"level":"error","ts":1725947776.1756518,"logger":"go.opentelemetry.io/auto","caller":"cli/main.go:121","msg":"instrumentation crashed","error":"invalid offset for the field in version: net/url.URL:OmitHost (1.18.0)","stacktrace":"main.main\n\t/app/cli/main.go:121\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:271"}

Anyone know which step I am missing. Thank you.

**Comment by lmhinnel** [comment]
Change to `go 1.22.1` and `otel/autoinstrumentation-go:v0.13.0-alpha`. Idk why, but it works.

**Comment by MrAlias** [comment]
Resolved by offsets update as pointed out in https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/1079#issuecomment-2339989279

**Comment by Danny5487401** [comment]
https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/1836
