### ISSUE TITLE
golang func parameter index with uprobe consult

### ISSUE THREAD

**Issue by chentao-kernel** [open-telemetry/opentelemetry-go-instrumentation#1176]
### Describe the bug
Hi guys, when get golang func parameter with uprobe here ReponseWirter parater index is 3, i kown serverHandler struct is the first parameter in fact, but why  ReponseWirter is 3 not 2, the same as req_ptr
![image](https://github.com/user-attachments/assets/8e193061-2d29-4c75-b63c-4856deb92e95)

### Environment

 - OS: [e.g. iOS, Windows]
 - Go Version: [e.g. 1.6]
 - Version: [e.g. 1295520, v0.1.0]

**Comment by damemi** [comment]
@MrAlias explained the numbering to me as roughly structs are worth 1 index and interfaces are worth 2 (one for the itab + one for the data pointer)

So the serverHandler struct is 1 + (skip 1 for ResponseWriter itab) + 1 for ResponseWriter data = 3. Then Req ptr = 3+1 = 4

Him or @RonFed can probably explain it better, but that's my understanding

**Comment by MrAlias** [comment]
As @damemi correctly points out,, that probe instruments:

```go
func (sh serverHandler) ServeHTTP(rw ResponseWriter, req *Request)
```

The arguments passed in the assembly code (and equivalently in the produced machine code) are:

1. The value receiver `serverHandler`
2. The `ResponseWriter` interface `itab`
3. The `ResponseWriter` interface data pointer
4. The `Request` pointer

I'm going to close this as this should answer this question. Please re-open if not.
