### ISSUE TITLE
The offset for golang.org/x/net/http2.FrameHeader.StreamID in the offset_results.json file was incorrectly generated for version 0.8.0

### ISSUE THREAD

**Issue by bittercookie** [open-telemetry/opentelemetry-go-instrumentation#1204]
### Describe the bug

The offset for golang.org/x/net/http2.FrameHeader.StreamID  in [the offset_results.json](https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/main/internal/pkg/inject/offset_results.json#1546) for version 0.8.0 should be the same as other versions.

[the source for v0.7.0](https://pkg.go.dev/golang.org/x/net@v0.7.0/http2#FrameHeader)
[the source for v0.8.0](https://pkg.go.dev/golang.org/x/net@v0.8.0/http2#FrameHeader)
[the source for v0.9.0](https://pkg.go.dev/golang.org/x/net@v0.9.0/http2#FrameHeader)

**Comment by RonFed** [comment]
Thanks for reporting this.
It looks like it was a regression in https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/1044/files#diff-15a322f23067198dc3f6baea35decb97f02a703fe637d6191e9871c5bf43d564

We encountered a similar case in the past of wrong offsets generated.
@MrAlias  @damemi

**Comment by damemi** [comment]
Thanks for finding that @RonFed, I'll see if I can regenerate a fix

**Comment by damemi** [comment]
Opened https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/1206 to fix
