### ISSUE TITLE
Improve Instrumentation.Run API

### ISSUE THREAD

**Issue by RonFed** [open-telemetry/opentelemetry-go-instrumentation#1240]
Currently, our Run function is:
1. Blocking
2. Has 2 main parts - 
         a) Initializing the probes - loading and attaching them.
         b) Running the main events loop.
After the first part is done we close the loaded indicator.

The main disadvantage to this design is the error reporting to the user.
A typical use case might be:

```Go
	go func() {
		err := inst.Run(ctx)
		if err != nil {
			Logger.Error(err, "failed to run instrumentation")
		}
		runError <- err
	}()

       // we want to make sure the instrumentation is loaded before we continue

	select {
	case <-loadedIndicator:
	     Logger.Info("instrumentation loaded")
	case <-runError:
            // error returned from run - this can be either a loading error or a closing error
	}
```

One possible solution for this is to split the `Run` function into `Load` and `Run` - this way we can remove the loaded indicator. 
`Load` won't be blocking and will do the first part of what `Run` is doing toady.
In addition, the errors returned from Load and Run are well-defined and won't have possible double meaning.

After this change the above code can be changed to something like:
```Go
        err := inst.Load(ctx)
        if err != nil {
              return err
        }

         // the instrumentation is loaded and ready to send data

	go func() {
		err := inst.Run(ctx)
		if err != nil {
			Logger.Error(err, "failed to run instrumentation")
		}

               // the instrumentation is closed, report possible closing errors
                if err != nil {
		         closingErrors <- err
               }
	}()

     //Continue doing other stuff, possibly listening in the background on the closingErrors channel for closing errors

```

**Comment by MrAlias** [comment]
SIG meeting notes:

- Default behavior if `Run` is called before `Load` is to return an error. We may iterate on this behavior in the future as need arises.
