### ISSUE TITLE
Release v0.2.0-alpha

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-instrumentation#131]
- https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/138

**Comment by MrAlias** [comment]
Try to include https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/128

**Comment by MrAlias** [comment]
https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/120

**Comment by MrAlias** [comment]
https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/129

**Comment by TylerHelmuth** [comment]
Ready to close
