### ISSUE TITLE
Review LogSize configuration

### ISSUE THREAD

**Issue by MikeGoldsmith** [open-telemetry/opentelemetry-go-instrumentation#136]
Review hardcoded logsize and whether we should allow users to adjust via configuration.

_Originally posted by @MikeGoldsmith in https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/128#pullrequestreview-1409363569_

**Comment by edeNFed** [comment]
Copying my comment from the original thread:

> 
> The default size is 1024 bytes, which may not be enough for all eBPF programs.
> This sets the size of the requested buffer allocated from the kernel when loading eBPF programs. Allowing users to control it may have some security concerns (for example, setting a really high value causing huge memory allocation)

**Comment by MrAlias** [comment]
Verifier log size was removed in https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/965. Upstream removed the need to configure this: https://github.com/cilium/ebpf/releases.
