### ISSUE TITLE
Error while loading probes : samplers_config_map not found

### ISSUE THREAD

**Issue by jim-billy-zoho** [open-telemetry/opentelemetry-go-instrumentation#1372]
Dear Team, 
I started the agent using the below command

- sudo OTEL_GO_AUTO_TARGET_EXE=/home/go-banking-app/gobanking OTEL_SERVICE_NAME=go_banking_app OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4318 ./otel-go-instrumentation

and facing the below error 

- {"time":"2024-12-04T13:30:10.964564736+05:30","level":"INFO","source":{"function":"main.main","file":"/home/go_my_private_projects/opentelemetry-go-instrumentation/cli/main.go","line":103},"msg":"building OpenTelemetry Go instrumentation ...","globalImpl":false,"version":{"Release":"v0.18.0-alpha","Revision":"1fb7ebdf0c2838bb855fde721bc0564f43abfaec-dirty","Go":{"Version":"go1.22.7","OS":"linux","Arch":"amd64"}}}

- {"time":"2024-12-04T13:30:12.971588664+05:30","level":"INFO","source":{"function":"go.opentelemetry.io/auto/internal/pkg/process.(*Analyzer).DiscoverProcessID","file":"/home/go_my_private_projects/opentelemetry-go-instrumentation/internal/pkg/process/discover.go","line":64},"msg":"found process","pid":3343901}

- {"time":"2024-12-04T13:30:12.975055978+05:30","level":"INFO","source":{"function":"go.opentelemetry.io/auto/internal/pkg/process.remoteAllocate.func1","file":"/home/go_my_private_projects/opentelemetry-go-instrumentation/internal/pkg/process/allocate.go","line":70},"msg":"Detaching from process","pid":3343901}

- {"time":"2024-12-04T13:30:12.975091258+05:30","level":"INFO","source":{"function":"go.opentelemetry.io/auto.NewInstrumentation","file":"/home/go_my_private_projects/opentelemetry-go-instrumentation/instrumentation.go","line":113},"msg":"target process analysis completed","pid":3343901,"go_version":"1.22.4","dependencies":{"filippo.io/edwards25519":"1.1.0","github.com/go-sql-driver/mysql":"1.8.1","std":"1.22.4"},"total_functions_found":5}

- {"time":"2024-12-04T13:30:12.975376111+05:30","level":"INFO","source":{"function":"go.opentelemetry.io/auto/internal/pkg/instrumentation.(*Manager).loadProbes","file":"/home/go_my_private_projects/opentelemetry-go-instrumentation/internal/pkg/instrumentation/manager.go","line":375},"msg":"\n"}

- {"time":"2024-12-04T13:30:13.232097643+05:30","level":"INFO","source":{"function":"go.opentelemetry.io/auto/internal/pkg/instrumentation/probe.(*Base[...]).Load","file":"/home/go_my_private_projects/opentelemetry-go-instrumentation/internal/pkg/instrumentation/probe/probe.go","line":139},"msg":"probe.go : Load( collection : ","!BADKEY":{"Programs":{"uprobe_serverHandler_ServeHTTP":{"VerifierLog":""},"uprobe_serverHandler_ServeHTTP_Returns":{"VerifierLog":""}},"Maps":{".rodata":{},".rodata.str1.1":{},"alloc_map":{},"events":{},"go_context_to_sc":{},"golang_mapbucket_storage_map":{},"http_server_uprobe_storage_map":{},"http_server_uprobes":{},"slice_array_buff_map":{},"tracked_spans_by_sc":{}}}}

- {"time":"2024-12-04T13:30:13.23217645+05:30","level":"ERROR","source":{"function":"go.opentelemetry.io/auto/internal/pkg/instrumentation.(*Manager).loadProbes","file":"/home/go_my_private_projects/opentelemetry-go-instrumentation/internal/pkg/instrumentation/manager.go","line":379},**"msg":"error while loading probes, cleaning up","error":"map samplers_config_map not found"**,"name":{"SpanKind":2,"InstrumentedPkg":"net/http"}}

- {"time":"2024-12-04T13:30:13.299331323+05:30","level":"ERROR","source":{"function":"main.main","file":"/home/go_my_private_projects/opentelemetry-go-instrumentation/cli/main.go","line":125},"msg":"failed to load instrumentation","error":"map samplers_config_map not found"}

samplers_config_map is not present in the ebpf collection 

Am I missing some input options?

**Comment by MrAlias** [comment]
```
"version":{"Release":"v0.18.0-alpha","Revision":"1fb7ebdf0c2838bb855fde721bc0564f43abfaec-dirty","Go":{"Version":"go1.22.7","OS":"linux","Arch":"amd64"}}}
```

It looks like you are using a modified version of the code from an non-release commit. Do you have the same issue when you use a release version?

**Comment by jim-billy-zoho** [comment]
> ```
> "version":{"Release":"v0.18.0-alpha","Revision":"1fb7ebdf0c2838bb855fde721bc0564f43abfaec-dirty","Go":{"Version":"go1.22.7","OS":"linux","Arch":"amd64"}}}
> ```
> 
> It looks like you are using a modified version of the code from an non-release commit. Do you have the same issue when you use a clean release version?

@MrAlias Thank you. Switching to a clean release version using the below command solved the issue.
git checkout tags/v0.18.0-alpha
