### ISSUE TITLE
Support `google.golang.org/grpc` `v1.69.0`

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-instrumentation#1421]
The function `google.golang.org/grpc/internal/transport.(*http2Server).WriteStatus` was renamed to `function google.golang.org/grpc/internal/transport.(*http2Server).writeStatus`: https://github.com/grpc/grpc-go/blob/317271b232677b7869576a49855b01b9f4775d67/internal/transport/http2_server.go#L1045

_Originally posted by @MrAlias in https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/1416#issuecomment-2540145321_

**Comment by MrAlias** [comment]
Looking at updating our definition of `probe.Uprobe` to handle this behavior split.

**Comment by damemi** [comment]
@MrAlias what are you thinking for the split? We have the MinVersion struct right now but I could see that getting messy, especially for situations where it's just a rename. Do you have an idea?

**Comment by MrAlias** [comment]
I'm still prototyping, but the current idea is to update the `Uprobe` with a version matching criteria and evaluate this during `loadProbe`.

**Comment by MrAlias** [comment]
It looks like `handleStream`'s signature also changed: https://github.com/grpc/grpc-go/blob/317271b232677b7869576a49855b01b9f4775d67/server.go#L1735

Still working on it.

**Comment by MrAlias** [comment]
Update: The parent span context is no longer being found for the server spans. Digging into why.

**Comment by MrAlias** [comment]
> Update: The parent span context is no longer being found for the server spans. Digging into why.

`http2Server.operateHeaders` also changed: https://github.com/grpc/grpc-go/commit/2a18bfcb16f3b7961ff28c902753c0b75e7d3ed8#diff-4058722211b8d52e2d5b0c0b7542059ed447a04017b69520d767e94a9493409eL362-R362

This is where the parent span context is supposed to come from. Updating.
