### ISSUE TITLE
Audit and update `net/http` instrumentation to comply with HTTP semantic conventions

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-instrumentation#169]
https://github.com/open-telemetry/opentelemetry-specification/blob/84a5fa3d1ef42caae8f99f1b431504d7cdb9fffe/specification/trace/semantic_conventions/http.md

# Fixes needed

- [ ] Resolve questions in #740
- [ ] Should we handle `_OTHER` http request method?
- [ ] Conditional checks for including span status
- [ ] Do we need to set `error.type`?
- [ ] Set [`network.protocol.name`](http://network.protocol.name/) if not `http`
- [ ] Set `url.full`

**Comment by damemi** [comment]
@MrAlias is this closed by https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/708?

**Comment by damemi** [comment]
Going through https://opentelemetry.io/docs/specs/semconv/http/http-spans/#http-client-server-example:

# Name

> HTTP spans MUST follow the overall [guidelines for span names](https://github.com/open-telemetry/opentelemetry-specification/tree/v1.26.0/specification/trace/api.md#span).

> HTTP server span names SHOULD be {method} {http.route} if there is a (low-cardinality) http.route available (see below for the exact definition of the [{method}](https://opentelemetry.io/docs/specs/semconv/http/http-spans/#method-placeholder) placeholder).

Added in https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/740 

> If there is no (low-cardinality) http.route available, HTTP server span names SHOULD be [{method}](https://opentelemetry.io/docs/specs/semconv/http/http-spans/#method-placeholder).

Fallback in https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/740 

> HTTP client spans have no http.route attribute since client-side instrumentation is not generally aware of the “route”, and therefore HTTP client span names SHOULD be [{method}](https://opentelemetry.io/docs/specs/semconv/http/http-spans/#method-placeholder).
#740 only applies to server

> The {method} MUST be {http.request.method} if the method represents the original method known to the instrumentation. In other cases (when {http.request.method} is set to _OTHER), {method} MUST be HTTP.

Our instrumentation doesn’t handle _OTHER

> Instrumentation MUST NOT default to using URI path as span name, but MAY provide hooks to allow custom logic to override the default span name.

Need to follow up in https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/740#pullrequestreview-1977037391

# Status

> [Span Status](https://github.com/open-telemetry/opentelemetry-specification/tree/v1.26.0/specification/trace/api.md#set-status) MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges, unless there was another error (e.g., network error receiving the response body; or 3xx codes with max redirects exceeded), in which case status MUST be set to Error.

We always set Span Status: https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/c8f651da92197ead7858f6de63f437a270cfa709/internal/pkg/opentelemetry/controller.go#L73 but we never set the `Status` field in HTTP [client](https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/c8f651da92197ead7858f6de63f437a270cfa709/internal/pkg/instrumentation/bpf/net/http/client/probe.go#L205-L211) or [server](https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/c8f651da92197ead7858f6de63f437a270cfa709/internal/pkg/instrumentation/bpf/net/http/server/probe.go#L211-L220) probes.

> For HTTP status codes in the 4xx range span status MUST be left unset in case of SpanKind.SERVER and MUST be set to Error in case of SpanKind.CLIENT.

> For HTTP status codes in the 5xx range, as well as any other code the client failed to interpret, span status MUST be set to Error.

Currently no conditional handling

> Don’t set the span status description if the reason can be inferred from http.response.status_code.

N/A - we don’t set description in client or server code

> HTTP request may fail if it was cancelled or an error occurred preventing the client or server from sending/receiving the request/response fully.

> When instrumentation detects such errors it MUST set span status to Error and MUST set the error.type attribute.

We don’t do this from what I can tell.

# Required attributes

* `error.type` (conditional, if request ended in error) - Not set
* `http.request.method` (required) - Set in [client](https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/c8f651da92197ead7858f6de63f437a270cfa709/internal/pkg/instrumentation/bpf/net/http/client/probe.go#L183) and [server](https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/c8f651da92197ead7858f6de63f437a270cfa709/internal/pkg/instrumentation/bpf/net/http/server/probe.go#L181) 
* `http.request.method_original` (required only if different from `http.request.method`) - N/A
* `http.response.status_code` (required if and only if one was received/sent) - Currently set always in [client](https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/c8f651da92197ead7858f6de63f437a270cfa709/internal/pkg/instrumentation/bpf/net/http/client/probe.go#L185) and [server](https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/c8f651da92197ead7858f6de63f437a270cfa709/internal/pkg/instrumentation/bpf/net/http/server/probe.go#L183) 
* `[network.protocol.name](http://network.protocol.name/)` (required if not `http` and `network.protocol.version` is set) - We always set `network.protocol.version` in [client](https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/c8f651da92197ead7858f6de63f437a270cfa709/internal/pkg/instrumentation/bpf/net/http/client/probe.go#L201) and [server](https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/c8f651da92197ead7858f6de63f437a270cfa709/internal/pkg/instrumentation/bpf/net/http/server/probe.go#L207) but don’t check if `[protocol.name](http://protocol.name/)` is not `http`

# HTTP Client

> This span type represents an outbound HTTP request. There are two ways this can be achieved in an instrumentation:

> 1. Instrumentations SHOULD create an HTTP span for each attempt to send an HTTP request over the wire. In case the request is resent, the resend attempts MUST follow the [HTTP resend spec](https://opentelemetry.io/docs/specs/semconv/http/http-spans/#http-request-retries-and-redirects). In this case, instrumentations SHOULD NOT (also) emit a logical encompassing HTTP client span.

> 2. If for some reason it is not possible to emit a span for each send attempt (because e.g. the instrumented library does not expose hooks that would allow this), instrumentations MAY create an HTTP span for the top-most operation of the HTTP client. In this case, the url.full MUST be the absolute URL that was originally requested, before any HTTP-redirects that may happen when executing the request.

> For an HTTP client span, SpanKind MUST be Client.

[Set in client Probe](https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/c8f651da92197ead7858f6de63f437a270cfa709/internal/pkg/instrumentation/bpf/net/http/client/probe.go#L49) 

## Required attributes

* `server.address` (required) - [Set](https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/c8f651da92197ead7858f6de63f437a270cfa709/internal/pkg/instrumentation/bpf/net/http/client/probe.go#L191) and checks for valid format
* `server.port` (required) - [Set](https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/c8f651da92197ead7858f6de63f437a270cfa709/internal/pkg/instrumentation/bpf/net/http/client/probe.go#L194) and checks for valid format
* `url.full` (required) - Not currently set. We set [`URLPath`](https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/c8f651da92197ead7858f6de63f437a270cfa709/internal/pkg/instrumentation/bpf/net/http/client/probe.go#L184) but this should be [`URLFull`](https://pkg.go.dev/go.opentelemetry.io/otel/semconv/v1.21.0#URLFull) 

# Server

> HTTP server instrumentations SHOULD do the best effort when populating server.address and server.port attributes and SHOULD determine them by using the first of the following that applies:

> * The original host which may be passed by the reverse proxy in the [Forwarded#host](https://developer.mozilla.org/docs/Web/HTTP/Headers/Forwarded#host), [X-Forwarded-Host](https://developer.mozilla.org/docs/Web/HTTP/Headers/X-Forwarded-Host), or a similar header.
> * The [:authority](https://tools.ietf.org/html/rfc9113#section-8.3.1) pseudo-header in case of HTTP/2 or HTTP/3
> * The [Host](https://tools.ietf.org/html/rfc7230#section-5.4) header.

We just use [the original Host](https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/c8f651da92197ead7858f6de63f437a270cfa709/internal/pkg/instrumentation/bpf/net/http/server/probe.go#L196) 

# Fixes needed

* Resolve questions in #740
* Should we handle `_OTHER` http request method?
* Conditional checks for including span status
* Do we need to set `error.type`?
* Set `[network.protocol.name](http://network.protocol.name/)` if not `http`
* Set `url.full`
