### ISSUE TITLE
OTEL_GO_AUTO_TARGET_EXE process not found

### ISSUE THREAD

**Issue by gauravluckme** [open-telemetry/opentelemetry-go-instrumentation#187]
The path OTEL_GO_AUTO_TARGET_EXE has been provided and the executable is also there at the container path.

However the Go auto instrumentation is not able to find it.

Error: "process not found yet, trying again soon"

**Comment by gauravluckme** [comment]
N/A

**Comment by zengyuxing007** [comment]
I encountered the same problem.

```shell
{"level":"info","ts":1698304109.2718306,"caller":"process/discover.go:61","msg":"process not found yet, trying again soon","exe_path":"/app/main"}
{"level":"info","ts":1698304111.2719026,"caller":"process/discover.go:61","msg":"process not found yet, trying again soon","exe_path":"/app/main"}
{"level":"info","ts":1698304113.2719774,"caller":"process/discover.go:61","msg":"process not found yet, trying again soon","exe_path":"/app/main"}
```

**Comment by zengyuxing007** [comment]
> I encountered the same problem.
> 
> ```shell
> {"level":"info","ts":1698304109.2718306,"caller":"process/discover.go:61","msg":"process not found yet, trying again soon","exe_path":"/app/main"}
> {"level":"info","ts":1698304111.2719026,"caller":"process/discover.go:61","msg":"process not found yet, trying again soon","exe_path":"/app/main"}
> {"level":"info","ts":1698304113.2719774,"caller":"process/discover.go:61","msg":"process not found yet, trying again soon","exe_path":"/app/main"}
> ```

should added this to the pod spec:

```yaml
    spec:
      shareProcessNamespace: true
```
