### ISSUE TITLE
Organize `docs/getting-started`

### ISSUE THREAD

**Issue by dineshg13** [open-telemetry/opentelemetry-go-instrumentation#196]
Currently `docs/getting-started` contains an example of how to use go-instrumentation with emojivoto. 

**Describe the solution you'd like**
The getting started folder should describe how to deploy and use go-instrumentation library. emojivoto example should be moved to `examples` folder.

**Comment by MrAlias** [comment]
Related https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/204

**Comment by damemi** [comment]
I've got some time and happy to pick this up
