### ISSUE TITLE
Donation proposal: OpenTelemetry Go Automatic Instrumentation

### ISSUE THREAD

**Issue by edeNFed** [open-telemetry/opentelemetry-go-instrumentation#2]
### Description of donated project

This project adds OpenTelemetry instrumentation to Go applications without having to modify their source code.
Instrumentation is done by using [eBPF](https://ebpf.io) uprobes.

Automatic instrumentation is available for a wide range of Go applications: Go version 1.12 and above, in addition to supporting stripped binaries (compiled with `go build -ldflags "-s -w"`)

Instrumented libraries follow the [OpenTelemetry specification](https://github.com/open-telemetry/opentelemetry-specification) and semantic conventions to produce standard OpenTelemetry data.

GitHub repos:
https://github.com/keyval-dev/opentelemetry-go-instrumentation
https://github.com/keyval-dev/offsets-tracker (used by this project, can also be donated if needed)

A detailed technical explanation is documented [here](https://github.com/keyval-dev/opentelemetry-go-instrumentation/blob/master/docs/how-it-works.md).

### Summary of existing usage of donated project

This project is a core part of [keyval](https://keyval.dev)'s product and production systems.
We are using this instrumentation successfully on many Go applications including multiple popular open-source Go projects.

#### OpenTelemetry Adoption
Go is the most popular programming language in the CNCF landscape (see [DevStats](https://all.devstats.cncf.io/d/67/licenses-and-programming-languages?orgId=1&from=1650283292149&to=1652875292149&viewPanel=13))
Providing automatic instrumentation for Go applications would allow projects without the resources needed for implementing manual instrumentation to easily adopt OpenTelemetry. 

#### Alignment
Currently, automatic instrumentation exists for [Python](https://github.com/open-telemetry/opentelemetry-python), [.NET](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation), [JavaScript](https://github.com/open-telemetry/opentelemetry-js), and [Java](https://github.com/open-telemetry/opentelemetry-java-instrumentation). Our goal is to provide the same level of automatic instrumentation for Go applications. We hope this project will lead the way for automatic instrumentation for other compiled languages such as Rust and C++ which may also be implemented using eBPF.

#### Security

Running eBPF programs requires elevated privileges. We believe that being part of the OpenTelemetry community would make users more comfortable using this project.

### Maintenance plan

Keyval will continue to maintain this project and we welcome the opportunity to work with more contributors.
Multiple developers in the OpenTelemetry community (from Go SDK SIG, Operator SIG & eBPF SIG) and in the eBPF community have expressed interest in contributing to this project.

Our current roadmap contains the following tasks:
1. Adding more instrumentations (with PostgreSQL and MySQL coming soon)
2. Integration with Go manual instrumentation
3. Better goroutine id tracking (supporting more complex scenarios)
4. Add Go as part of automatic instrumentation done by [OpenTelemetry Operator](https://github.com/open-telemetry/opentelemetry-operator) - [In Progress](https://github.com/open-telemetry/opentelemetry-operator/pull/973)
5. Context propagation
6. Metrics support

### Existing software license(s)
This project is licensed under the terms of the Apache 2.0 open source license.

### List of trademarks (if any)

None

**Comment by jmacd** [comment]
I've tranfered this issue. We can close this when the donation has been merged. Thanks, @edeNFed

**Comment by edeNFed** [comment]
Opened #4

**Comment by dineshg13** [comment]
@edeNFed The go-instrumentation uses https://github.com/keyval-dev/offsets-tracker to generate `offset_results.json`, I believe that is the critical input to the code. What are your thoughts , on how this work once the code is merged ? 
Ideally , i believe offsets-tracker should be part of `open-telemetry` , but would be like to know your thoughts .

**Comment by edeNFed** [comment]
Hi @dineshg13 I totally agree (I mentioned the offset tracker repo in the original donation proposal). Not sure if this is needed as a first step but ultimately I also think this should be owned by the community.

**Comment by dineshg13** [comment]
Thanks @edeNFed , i don't think it is necessary as a first step. We can add it to our roadmap

**Comment by dineshg13** [comment]
Closing issue as PR is merged.
