### ISSUE TITLE
Add Logging/File Exporter Support.

### ISSUE THREAD

**Issue by dineshg13** [open-telemetry/opentelemetry-go-instrumentation#210]
Go - Auto instruments currently only supports OTLP exporter. We should also add support for Logging & file exporters. `OTEL_TRACES_EXPORTER` can used to specify the exporter, default being OTLP.   Tests can use file exporters for tests instead of spinning up a collector.

**Comment by MrAlias** [comment]
Resolved by https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/426
