### ISSUE TITLE
Document supported environment variables

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go-instrumentation#229]
We should have a dedicated page with all possible configuration settings. Example from .NET Automatic Instrumentation: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/config.md

Here is how we can find some env vars coming from this repo: https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-go-instrumentation%20%22OTEL_&type=code

We need to remember to also document config which comes from the dependencies e.g. 
- https://pkg.go.dev/go.opentelemetry.io/contrib/exporters/autoexport  (only the ones related with tracing)
- https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc
- https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp

I think these env vars are supported as well (documentation for these env vars: https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/):
- `OTEL_SPAN_ATTRIBUTE_COUNT_LIMIT`
- `OTEL_SPAN_ATTRIBUTE_VALUE_LENGTH_LIMIT`
- `OTEL_SPAN_EVENT_COUNT_LIMIT`
- `OTEL_SPAN_LINK_COUNT_LIMIT`
- `OTEL_EVENT_ATTRIBUTE_COUNT_LIMIT`
- `OTEL_LINK_ATTRIBUTE_COUNT_LIMIT`
- ~~`OTEL_ATTRIBUTE_VALUE_LENGTH_LIMIT`~~ (IMO it is better not to document this env var as it is [not documented in OTel Go SDK](https://pkg.go.dev/go.opentelemetry.io/otel/sdk/trace#NewSpanLimits) also other env vars offer more fine-grained control)
- ~~`OTEL_ATTRIBUTE_COUNT_LIMIT`~~ (IMO it is better not to document this env var as it is [not documented in OTel Go SDK](https://pkg.go.dev/go.opentelemetry.io/otel/sdk/trace#NewSpanLimits) also other env vars offer more fine-grained control)

**Comment by MA3CIN** [comment]
Bump - As a new user, this is still very much needed. Perhaps some info could be added in the "Configuration" section of the README?

**Comment by damemi** [comment]
Also from #233:

> We should have a dedicated page with all possible configuration settings. Example from .NET Automatic Instrumentation: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/config.md
> 
> Remember to also document config which comes from the dependencies e.g. https://github.com/open-telemetry/opentelemetry-go/tree/main/exporters/otlp/otlptrace#environment-variables

**Comment by pellared** [comment]
@open-telemetry/go-instrumentation-maintainers, can you double-check if I have not missed any important reference in the issue description? Should someone wanting to document all env vars be able to find all env vars?

**Comment by MrAlias** [comment]
Looks like a good starting point to me 👍

**Comment by MrAlias** [comment]
On second thought, we don't handle any events. No need to document those conf opts.
