### ISSUE TITLE
Document configuration 

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go-instrumentation#233]
We should have a dedicated page with all possible configuration settings. Example from .NET Automatic Instrumentation: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/config.md

Remember to also document config which comes from the dependencies e.g. https://github.com/open-telemetry/opentelemetry-go/tree/main/exporters/otlp/otlptrace#environment-variables

**Comment by damemi** [comment]
Closing as #229 can cover this
