### ISSUE TITLE
stdouttrace exporter

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go-instrumentation#234]
We should add support for setting/enabling [stdouttrace](https://github.com/open-telemetry/opentelemetry-go/tree/main/exporters/stdout/stdouttrace) exporter.

This is very helpful during troubleshooting and debugging.

We might consider to add a dedicated env var to set it as there is "known value" defined by [the specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/configuration/sdk-environment-variables.md). E.g. `OTEL_GO_AUTO_TRACES_STDOUT_EXPORTER_ENABLED`.

**Comment by codeboten** [comment]
Would be happy to take this one on. What do you think of using the `OTEL_TRACES_EXPORTER=console` environment variable for this? See https://github.com/open-telemetry/opentelemetry-specification/pull/3742

**Comment by codeboten** [comment]
I made the comment before seeing @MrAlias's PR, it looks like that would allow any exporter available through the auto package?

**Comment by pellared** [comment]
> I made the comment before seeing @MrAlias's PR, it looks like that would allow any exporter available through the auto package?

Correct. Still the comment  is valuable.
