### ISSUE TITLE
Automate the update of offsets

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-instrumentation#25]
Currently this is done manually (i.e. https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/23), it should be automated.

**Comment by damemi** [comment]
I was wondering if it would be possible to automate this at runtime too. I think it would be useful if the auto-instrumentation agent had an option to just use the host's Go installation to calculate offsets. This would be useful in containerized apps where you may know/control the version of Go that the app runs on.

**Comment by MrAlias** [comment]
> I was wondering if it would be possible to automate this at runtime too. I think it would be useful if the auto-instrumentation agent had an option to just use the host's Go installation to calculate offsets. This would be useful in containerized apps where you may know/control the version of Go that the app runs on.

I would support this if it is possible. I definitely think it is worth looking into. :+1:

**Comment by damemi** [comment]
It would also support non-networked environments, as I believe the offset tracker gets its data from online sources (right?)
