### ISSUE TITLE
Audit needed for the Hashicorp MPL -> BUSL license change

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-instrumentation#254]
Related CNCF issue: https://github.com/cncf/foundation/issues/617

We need to ensure this will not affect our released binaries, and if it does we need to evaluate the impact.

**Comment by MrAlias** [comment]
According to the LICENSE director, https://github.com/hashicorp/go-version is the only hashicorp package we depend on and it remains to have a MPL-2.0 license.

**Comment by MrAlias** [comment]
Looking at our `go.sum` files to determine all transitive dependencies:

```sh
$ grep -Rn 'github.com/hashicorp' | grep 'go\.sum' | cut -d: -f3 | cut -d' ' -f1 | sort -u
github.com/hashicorp/errwrap
github.com/hashicorp/golang-lru
github.com/hashicorp/go-multierror
github.com/hashicorp/go-version
github.com/hashicorp/hcl
```

For this list:

- [x] github.com/hashicorp/errwrap: Still using MPL-2.0
  - https://github.com/hashicorp/errwrap/blob/3622ed43b5c382494ba1496673ff8d4a9d4f6ea7/LICENSE
- [x] github.com/hashicorp/golang-lru: Still using MPL-2.0
  - https://github.com/hashicorp/golang-lru/blob/3afaa48530f711754c178ceb61ff060d86c17b95/LICENSE
- [x] github.com/hashicorp/go-multierror: Still using MPL-2.0
  - https://github.com/hashicorp/go-multierror/blob/09fc6ae401b42e7af2af3bb1e9c02fdc7268be17/LICENSE
- [x] github.com/hashicorp/go-version: Still using MPL-2.0
  - https://github.com/hashicorp/go-version/blob/644291d14038339745c2d883a1a114488e30b702/LICENSE
- [x] github.com/hashicorp/hcl: Still using MPL-2.0
  - https://github.com/hashicorp/hcl/blob/527ec318631dc6db59da91e8ca7f205fc989ebc5/LICENSE

**Comment by MrAlias** [comment]
Double check using GitHub search: https://github.com/search?q=org%3Aopen-telemetry+repo%3Aopen-telemetry%2Fopentelemetry-go-instrumentation++hashicorp&type=code&p=1

Nothing found other than already reported.

**Comment by MrAlias** [comment]
Closing as the audit looks complete and no dependencies of the project are listed as having their licenses changed.

**Comment by frzifus** [comment]
Operator tracking issue: https://github.com/open-telemetry/opentelemetry-operator/issues/2038
