### ISSUE TITLE
v0.2.2-alpha permission denied for uprobe_Http2Client_CreateHeaderFields

### ISSUE THREAD

**Issue by Xwunderful** [open-telemetry/opentelemetry-go-instrumentation#255]
### Describe the bug

autoinstrumentation-go:v0.2.2-alpha container cannot run, indicating  program uprobe_Http2Client_CreateHeaderFields: load program: permission denied

### Environment

 - OS: linux/amd64, kernel 5.4.119-20.0009.20
 - Go Version: 1.20
 - Version: ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:v0.2.2-alpha

### To Reproduce

1. git pull ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:v0.2.2-alpha
2. docker run autoinstrumentation-go to instrument my program, docker run failure
3. docker command is : docker run  --privileged  --pid="host" --env OTEL_EXPORTER_OTLP_ENDPOINT="******" -e OTEL_PROPAGATORS=tracecontext,baggage -e OTEL_SERVICE_NAME=***** -e OTEL_GO_AUTO_TARGET_EXE="/go/bin/hotrod-linux" autoinstrumentation:v2 

### Expected behavior

Am I missing parameters when running the command? I want to run autoinstrumentation-go:v0.2.2-alpha correctly

### Additional context

`{"level":"info","ts":1692189502.8034875,"caller":"instrumentors/runner.go:85","msg":"loading instrumentor","name":"net/http/client"}
{"level":"info","ts":1692189502.8046474,"caller":"inject/injector.go:91","msg":"Injecting variables","vars":{"ctx_ptr_pos":232,"end_addr":140629049683968,"headers_ptr_pos":56,"is_registers_abi":true,"method_ptr_pos":0,"path_ptr_pos":56,"start_addr":140629024518144,"total_cpus":2,"url_ptr_pos":16}}
{"level":"info","ts":1692189502.8221781,"caller":"instrumentors/runner.go:85","msg":"loading instrumentor","name":"google.golang.org/grpc"}
{"level":"info","ts":1692189502.825116,"caller":"inject/injector.go:91","msg":"Injecting variables","vars":{"clientconn_target_ptr_pos":24,"end_addr":140629049683968,"is_registers_abi":true,"start_addr":140629024518144,"total_cpus":2}}
{"level":"error","ts":1692189502.8297305,"caller":"instrumentors/runner.go:88","msg":"error while loading instrumentors, cleaning up","name":"google.golang.org/grpc","error":"field UprobeHttp2ClientCreateHeaderFields: program uprobe_Http2Client_CreateHeaderFields: load program: permission denied: 817: (55) if r0 != 0x0 goto pc+122: R0_w=inv0 R3_w=inv(id=0) R6=fp-384 R7=invP0 R8=invP0 R9=inv(id=0) R10=fp0 fp-24=??????mm fp-32=mmmmmmmm fp-40=mmmmmmmm fp-48=mmmmmmmm fp-56=mmmmmmmm fp-64=mmmmmmmm fp-72=mmmmmmmm fp-80=mmmmmmmm fp-88=mmmmmmmm fp-96=mmmmmmmm fp-104=mmmmmmmm fp-112=?????mmm fp-120=mmmmmmmm fp-128=mmmmmmmm fp-136=mmmmmmmm fp-144=mmmmmmmm fp-152=mmmmmmmm fp-160=mmmmmmmm fp-168=mmmmmmmm fp-176=mmmmmmmm fp-184=mmmmmmmm fp-192=mmmmmmmm fp-200=mmmmmmmm fp-208=mmmmmmmm fp-216=mmmmmmmm fp-224=mmmmmmmm fp-232=mmmmmmmm fp-240=mmmmmmmm fp-248=mmmmmmmm fp-256=mmmmmmmm fp-264=mmmmmmmm fp-272=mmmmmmmm fp-280=mmmmmmmm fp-288=mmmmmmmm fp-296=mmmmmmmm fp-304=mmmmmmmm fp-312=mmmmmmmm fp-320=mmmmmmmm fp-384=mmmmmmmm fp-448=mmmmmmmm fp-456=ctx fp (truncated, 1144 line(s) omitted)","stacktrace":"go.opentelemetry.io/auto/pkg/instrumentors.(*Manager).load\n\t/app/pkg/instrumentors/runner.go:88\ngo.opentelemetry.io/auto/pkg/instrumentors.(*Manager).Run\n\t/app/pkg/instrumentors/runner.go:36\nmain.main\n\t/app/cli/main.go:86\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
{"level":"info","ts":1692189502.829796,"caller":"grpc/probe.go:240","msg":"closing gRPC instrumentor"}
{"level":"info","ts":1692189502.8298173,"caller":"server/probe.go:242","msg":"closing gRPC server instrumentor"}
{"level":"info","ts":1692189502.8298225,"caller":"server/probe.go:241","msg":"closing net/http instrumentor"}
{"level":"info","ts":1692189502.8402631,"caller":"client/probe.go:229","msg":"closing net/http/client instrumentor"}
{"level":"error","ts":1692189502.8892674,"caller":"cli/main.go:88","msg":"error while running instrumentors","error":"field UprobeHttp2ClientCreateHeaderFields: program uprobe_Http2Client_CreateHeaderFields: load program: permission denied: 817: (55) if r0 != 0x0 goto pc+122: R0_w=inv0 R3_w=inv(id=0) R6=fp-384 R7=invP0 R8=invP0 R9=inv(id=0) R10=fp0 fp-24=??????mm fp-32=mmmmmmmm fp-40=mmmmmmmm fp-48=mmmmmmmm fp-56=mmmmmmmm fp-64=mmmmmmmm fp-72=mmmmmmmm fp-80=mmmmmmmm fp-88=mmmmmmmm fp-96=mmmmmmmm fp-104=mmmmmmmm fp-112=?????mmm fp-120=mmmmmmmm fp-128=mmmmmmmm fp-136=mmmmmmmm fp-144=mmmmmmmm fp-152=mmmmmmmm fp-160=mmmmmmmm fp-168=mmmmmmmm fp-176=mmmmmmmm fp-184=mmmmmmmm fp-192=mmmmmmmm fp-200=mmmmmmmm fp-208=mmmmmmmm fp-216=mmmmmmmm fp-224=mmmmmmmm fp-232=mmmmmmmm fp-240=mmmmmmmm fp-248=mmmmmmmm fp-256=mmmmmmmm fp-264=mmmmmmmm fp-272=mmmmmmmm fp-280=mmmmmmmm fp-288=mmmmmmmm fp-296=mmmmmmmm fp-304=mmmmmmmm fp-312=mmmmmmmm fp-320=mmmmmmmm fp-384=mmmmmmmm fp-448=mmmmmmmm fp-456=ctx fp (truncated, 1144 line(s) omitted)","stacktrace":"main.main\n\t/app/cli/main.go:88\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}`

**Comment by RonFed** [comment]
I think https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/118 solves this. @edeNFed
