### ISSUE TITLE
Document instrumentation versioning compatibility

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-instrumentation#26]
For each support instrumented library document what version of the library are supported.

**Comment by damemi** [comment]
https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/725#issuecomment-2032609505 for other support compatibility requirements

**Comment by MrAlias** [comment]
Automation of this documentation is tracked in https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/908.
