### ISSUE TITLE
Donation proposal: OpenTelemetry source level automatic Go instrumentation

### ISSUE THREAD

**Issue by pdelewski** [open-telemetry/opentelemetry-go-instrumentation#3]
### Description of project

This project adds OpenTelemetry instrumentation (https://github.com/open-telemetry/opentelemetry-go) to Go applications by automatically modifying their source code in similar way as compiler. It can instrument any golang project. It depends only on standard libraries and is platform agnostic.

Current github repo:
https://github.com/SumoLogic-Labs/autotel

### Summary of existing usage of donated project
The project is developed and maintained by [Sumo Logic](https://www.sumologic.com/)
We are actively testing it with different Go applications and open source projects, 
extending test coverage and eliminating gaps. We are planning to start beta tests with customers soon.

### Benefits to the OpenTelemetry community

Project offers automatic instrumentation by modifying source code. It has similar goals as 
https://github.com/keyval-dev/opentelemetry-go-instrumentation
https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/2

but  tackles problem from different angle and has different tradeoffs:
- does not depend on external mechanisms like eBPF
- platform agnostic
- depends only on standard golang libraries and tooling
- require access to source code as modifies it (that might be advantage or disadvantage, depending on view, but if something will fail, it will fail at compile time)
- does not require elevated privileges

### Maintenance plan

We will continue to develop and maintain project. Our main goal is to expand awareness of existence of this project and
get feedback from community about needed features and usage scenarios. Another aspect is to get more
people involved contributing to this project. We are open to suggestions and ideas.

Our current roadmap is as follows:

1. Reliability and robustness, extending test coverage, testing with more applications and open source projects
2. Distributed tracing. Tracing services, processes that are using different types of IO in between
3. Integration with already intrumented code
4. Configurability. Selecting specific functions on the call graph to instrument, exporting output to different backends, etc...

### Existing software licenses
This project is licensed under the terms of the Apache 2.0 open source license.

### List of Trademarks (if any)
None

### Misc 
Not sure if that's right place or maybe better would be a https://github.com/open-telemetry/community cc @tigrannajaryan

**Comment by jmacd** [comment]
I've tranfered this issue. We can close this when the donation has been merged. Thanks, @pdelewski

**Comment by MrAlias** [comment]
It has been suggested that this is hosted in the otel Go contrib repository. Before that can happen https://github.com/open-telemetry/opentelemetry-go-contrib/issues/2834 needs to be resolved.

**Comment by pdelewski** [comment]
Closing as `instrgen` is finally merged into https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrgen
