### ISSUE TITLE
Publish an official OpenTelemetry image

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-go-instrumentation#31]
**Is your feature request related to a problem? Please describe.**
I am looking for an official OpenTelemetry image to use instead of `keyval/otel-go-agent:latest` but none exists yet.

**Describe the solution you'd like**
This repository publishes an image via Github/Dockerhub like other OpenTelemetry owned images.

**Describe alternatives you've considered**

**Additional context**
I feel a Community-owned image is required for https://github.com/open-telemetry/opentelemetry-operator/issues/908

**Comment by TylerHelmuth** [comment]
This is something I am invested in and can help as needed.

**Comment by edeNFed** [comment]
Opened: https://github.com/open-telemetry/community/issues/1377
