### ISSUE TITLE
Delete examples/rolldice

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go-instrumentation#340]
> Do we need a separate issue for moving `go.opentelemetry.io/auto/examples/rolldice` under `excluded:` after the next release?

The plan is to delete `go.mod` in `go.opentelemetry.io/auto/examples/rolldice` after the next release.

_Originally posted by @MrAlias in https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/337#issuecomment-1726319109_

**Comment by MrAlias** [comment]
Closed by #423
