### ISSUE TITLE
Add a WithEnv option

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-instrumentation#415]
**Is your feature request related to a problem? Please describe.**

Environment variable precedence is a subjective matter. Some users would like the passed options to take precedence to them and other would like the opposite.

It would be ideal if this was configurable

**Describe the solution you'd like**

Add a `WithEnv` `InstrumentationOption` that will parse the relevant environment variables and set config values.

The precedence of this option will be based on the order it is passed. If first, the following options will have precedence. And if last, it will have precedence.

**Comment by pellared** [comment]
> The precedence of this option will be based on the order it is passed.

Do we have other places where the order of option parameters matters.

AFAIK it is usually seen as an antipattern.

Reference: https://youtu.be/5uM6z7RnReE?si=clZ6TX3XlETobPiz&t=721

The problem if such design is that the user would need to read and remember the behavior described in the docs which is not obvious.

Maybe better adding and option like `WithEnvVarPrecedence`?

This is not a strong opinion. I am just giving feedback.

**Comment by MrAlias** [comment]
I'm not sure I follow. We already have a precedence of "last-option-wins" on any conflict. This would just be a continuation of that and it would remove the additional environment linking to each option.

**Comment by pellared** [comment]
>  We already have a precedence of "last-option-wins" on any conflict. This would just be a continuation of that and it would remove the additional environment linking to each option.

This answers my first question. Therefore, I think this issue is OK and I created a separate one https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/416.
