### ISSUE TITLE
Build Binary/Docker image for every PR

### ISSUE THREAD

**Issue by dineshg13** [open-telemetry/opentelemetry-go-instrumentation#42]
**Is your feature request related to a problem? Please describe.**
Ensure that every PR is able to build both docker image and binary on ubuntu

**Describe the solution you'd like**
* Ensure that code compiles on  every PR 
* We are able to build docker images on every PR

**Comment by damemi** [comment]
I believe we can close this with the test I added in https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/49
