### ISSUE TITLE
Support docker credentials in `offsetgen`

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-instrumentation#435]
**Is your feature request related to a problem? Please describe.**

When a developer runs a full offset update, or tries to add a new offset, on a new system without a cache of all the docker images of Go Dockerhub will rate-limit their requests for containers. This is something like 100 pulls a day, but more requests are needed for a completely new setup.

**Describe the solution you'd like**

Support user authentication in `offsetgen`. If it is set in the CLI or via the environment use that auth to pull images so the rate limit is not a blocker.

**Describe alternatives you've considered**

Currently you can work around this by authenticating with the docker CLI and just manually pulling all the images you need.

**Additional context**

https://docs.docker.com/docker-hub/download-rate-limit/

**Comment by damemi** [comment]
I'm hitting this now so just wanted to share what I've found: I think the docker functions like [`ImagePull](https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/493c236190c2c83406e97f770756c3c350145c3e/internal/tools/inspect/builder.go#L115) have an [Options struct](https://pkg.go.dev/github.com/docker/docker/api/types/image#PullOptions) that takes encoded registry auth credentials. Seems like we need to get the docker auth credentials locally at startup, base64 encode them, and pass them to these functions
