### ISSUE TITLE
Feature Request: Add support for `database/sql` package

### ISSUE THREAD

**Issue by smitthakkar96** [open-telemetry/opentelemetry-go-instrumentation#47]
**Is your feature request related to a problem? Please describe.**
Automatically generate spans for calls to SQL databases

**Describe the solution you'd like**
Add a new instrumentor for `datadbase/sql` under https://github.com/open-telemetry/opentelemetry-go-instrumentation/tree/main/pkg/instrumentors/bpf

**Describe alternatives you've considered**
Manual Instrumentation

**Comment by smitthakkar96** [comment]
Is the community accepting contributions for packages other than `http`, `grpc` and `mux`? Is there any documentation or guidelines on how to extend this further? It would be awesome if we could automatically generate spans for popular open-source packages, such as the list under https://github.com/DataDog/dd-trace-go/tree/main/contrib. I am happy to contribute, would like to know how I can get involved in this project?

**Comment by pellared** [comment]
> Is there any documentation or guidelines on how to extend this further?

I suggest starting by getting familiar with both https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/main/docs/how-it-works.md and https://github.com/open-telemetry/opentelemetry-go-instrumentation/tree/main/docs/getting-started.

**Comment by pellared** [comment]
I proposed to remove it from beta during last SIG meeting and nobody disagreed.
