### ISSUE TITLE
Auto-instrumentation tool

### ISSUE THREAD

**Issue by hedhyw** [open-telemetry/opentelemetry-go-instrumentation#5]
### Problem Statement

Manual declaration of spans introduces errors and is boring actually.

### Proposed Solution

I created [the tool](https://github.com/hedhyw/otelinji) that adds spans to all exported functions automatically if they have a context parameter. It supports templates and it will not add spans if they were already declared before.

My proposal is to add this to documentation or integrate it somehow if it would be useful for end users.

#### Alternatives

I didn't find any alternatives.

#### Prior Art

Generating layers: https://mattermost.com/blog/opentracing-for-go-projects/

### Additional Context

![image](https://user-images.githubusercontent.com/19246753/183383520-1e1885ea-567c-4824-b3d0-dbe953411b0f.png)

**Comment by Aneurysm9** [comment]
I have transferred this issue to the `opentelemetry-go-instrumentation` repo.  We are looking to establish a SIG for auto-instrumentation efforts in Go and this is a better fit there.

**Comment by pdelewski** [comment]
@hedhyw Look at https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/3

**Comment by pdelewski** [comment]
Closing, duplicate `instrgen` https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrgen
