### ISSUE TITLE
Fix the correctness of offsets

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-instrumentation#509]
The versions of the `google.golang.org/grpc/internal/transport` package below [`v1.14.0`](https://pkg.go.dev/google.golang.org/grpc@v1.14.0/internal/transport?tab=versions) do not exist, but they are reported in our offsets.

It also seems like merging #503 has unexpectedly filled in gaps.

The correctness of the offsets need to be addressed.

_Originally posted by @MrAlias in https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/503#discussion_r1394463028_

**Comment by MikeGoldsmith** [comment]
Following up here instead of the merged PR - guessing at an offset could be a security risk too. If for example, reading data from a HTTP headers, you could accidentally collect unintended data.
