### ISSUE TITLE
run examples/httpPlusdb, but did not grab sql statement

### ISSUE THREAD

**Issue by gophernancy** [open-telemetry/opentelemetry-go-instrumentation#521]
### Environment

 - OS: Linux hecs-402688 5.10.0-60.18.0.50.r865_35.hce2.x86_64 #1 SMP Sun Mar 26 18:01:01 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
 - Go Version: v1.21.3
 - Version: main

### To Reproduce

1. run jaeger v1.35.0
2. run opentelemetry-collector v0.42
3. run opentelemetry-go-instrumentation-main main
4. run examples/httpPlusdb 

### Expected behavior

From examples/httpPlusdb/http_Db_traces.jpg, it will grab sql statement. But I did not get sql statement. Can you help me?

### Additional context
<img width="1421" alt="image" src="https://github.com/open-telemetry/opentelemetry-go-instrumentation/assets/3292071/24b96e57-f14b-4474-9989-4d36ceaccd64">

**Comment by RonFed** [comment]
Can you please double check that you have `OTEL_GO_AUTO_INCLUDE_DB_STATEMENT=true` in the docker compose file?
If it is set correctly and you still can't see the query, please send the logs of the go-auto-instrumentation image.

**Comment by eugeneRover** [comment]
@RonFed thanks for the clue. I had to dive into [code](https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/main/internal/pkg/instrumentation/bpf/database/sql/probe.go#L113) so as to find it. This collector seems to be scarcely documented

**Comment by MrAlias** [comment]
It looks like https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/521#issuecomment-1822428522 resolves this. Closing.
