### ISSUE TITLE
Support slice attributes in eBPF

### ISSUE THREAD

**Issue by RonFed** [open-telemetry/opentelemetry-go-instrumentation#525]
As part of https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/523, eBPF code can parse float, int, string, and bool types as attributes.
We also need to add support for slice types for those (https://github.com/open-telemetry/opentelemetry-go/blob/main/attribute/value.go#L40).
for float, int, and bool slices, the solution should be straightforward using the same buffer used for all the values (max float slice size = size of buffer / size of float).
For string slices it requires more encoding work - I tried an initial implementation in which strings are packed into the value buffer and are separated by null bytes - but making it pass the eBPF verifier in different kernel versions was challenging.

**Comment by MrAlias** [comment]
Closing in favor of https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/954
