### ISSUE TITLE
Instrument `SetAttributes` from default OTel default global impl

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-instrumentation#539]
_Originally posted by @MrAlias in https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/523#discussion_r1408318459_

**Comment by asecondo** [comment]
👋 i'll grab this one

**Comment by asecondo** [comment]
actually, question for @RonFed - what's the intention behind this instrumentation? there's no `SetError` equivalent in the Span interface to map back to in the Go code and it looks like it only exists in the non recording span struct. is this instrumentation required?

**Comment by RonFed** [comment]
> actually, question for @RonFed - what's the intention behind this instrumentation? there's no `SetError` equivalent in the Span interface to map back to in the Go code and it looks like it only exists in the non recording span struct. is this instrumentation required?

Not sure.
@MrAlias can you elaborate on this one?

**Comment by MrAlias** [comment]
Right, I think that was a mistake. This should have been for `SetAttributes`. Updated.

**Comment by RonFed** [comment]
> Right, I think that was a mistake. This should have been for `SetAttributes`. Updated.

We have an instrumentation for that function, so maybe we can close this issue.
