### ISSUE TITLE
Starting auto-instrument again encounters crash

### ISSUE THREAD

**Issue by fyuan1316** [open-telemetry/opentelemetry-go-instrumentation#578]
### Describe the bug

First of all I would like to say that this is a great program!

While playing around with it I noticed that when keeping the application running and starting the go-instrument program again, the auto-instrument crashes with the error that the directory already exists.

`
{"level":"info","ts":1704449313.7016501,"logger":"Instrumentation.Manager","caller":"instrumentation/manager.go:107","msg":"no functions found for probe, removing","name":"google.golang.org/grpc/client"}
{"level":"info","ts":1704449313.701675,"logger":"Instrumentation.Manager","caller":"instrumentation/manager.go:107","msg":"no functions found for probe, removing","name":"google.golang.org/grpc/server"}
{"level":"info","ts":1704449313.7017107,"logger":"go.opentelemetry.io/auto","caller":"cli/main.go:107","msg":"starting instrumentation..."}
{"level":"info","ts":1704449314.4905517,"logger":"Instrumentation.Manager","caller":"instrumentation/manager.go:177","msg":"Mounting bpffs","allocations_details":{"StartAddr":140642395824128,"EndAddr":140642396217344}}
{"level":"error","ts":1704449315.5017455,"logger":"go.opentelemetry.io/auto","caller":"cli/main.go:109","msg":"instrumentation crashed","error":"mkdir /sys/fs/bpf/93325: file exists","stacktrace":"main.main\n\t/workspaces/opentelemetry-go-instrumentation/cli/main.go:109\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267"}
Process 110286 has exited with status 0
Detaching
`

I think that when acting as a sidecar for an application, the life cycle of auto-instrument and the application should be the same. So theoretically, it seems this is not a problem in use. However, for development and debugging, it still doesn't feel very convenient. It seems better to deal with it, what do you think, will this have other side effects?

### Environment

 - OS: [ubuntu]
 - Go Version: [1.21.5]
 - Version: [main branch]

**Comment by RonFed** [comment]
When stopping the instrumentation process using SIGTERM or SIGINT a proper cleanup should happen, however using SIGKILL will not. see https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/408#issuecomment-1784177965
