### ISSUE TITLE
(otelglobal): issues when processing span.SetAttributes() multiple times on a recording span

### ISSUE THREAD

**Issue by asecondo** [open-telemetry/opentelemetry-go-instrumentation#592]
### Describe the bug

Currently, processing multiple `span.SetAttributes(...)` calls in the EBPF C code has 2 main issues:

1. Calling `span.SetAttributes(...)` consecutively either completely wipes or partially wipes the existing attributes. In the case where `span.SetAttributes(...)` is called back-to-back with a single attribute, the second attribute will always replace the first attribute. This is due to always resetting the `valid_attrs` variable back to 0 to reindex back into the `enc_attrs` struct, resulting in a partial or complete wipe of the existing attributes.
2. Due to the previous issue, calling `span.SetAttributes(...)` consecutively also does not zero out the existing key and value byte arrays. Due to this, if the initial attribute key and/or value had a longer byte array, the second call will include key and value chars from the previous key and value.

### Environment

 - OS: Windows, but not OS specific
 - Go Version: 1.21.1, but not Go version specific
 - Version: v0.10.0-alpha

### To Reproduce

3. Click on '....'
4. Scroll down to '....'
5. See error

1. Modify the otelglobal e2e test's innerFunction to include the following additional `span.SetAttributes(...)` call:
```
span.SetAttributes(attribute.String("inner.key", "inner.value")) // currently exists
span.SetAttributes(attribute.String("idontthinkillseethis", "value")) // new
```
2. Run e2e test with `make fixture-otelglobal`
3. Notice lack of additional attribute, as well as key and value overwrites (from diff):
```
                  "attributes": [
                    {
   -                  "key": "inner.key",
   +                  "key": "idontthinkillseethis",
                      "value": {
   -                    "stringValue": "inner.value"
   +                    "stringValue": "value.value"
                      }
                    }
                  ],
```

### Expected behavior

1. Span attributes should be appended, not removed.
2. Span attribute key values should be wiped, if desired behavior is to completely replace.

### Additional context

I propose that the desired behavior should be to not replace any existing attribute key values. Instead, we should always append attribute key values and defer de-duplication logic to the Otel SDK.

**Comment by RonFed** [comment]
I agree, setting the `valid_attrs` to 0 on each call to `SetAttributes` is a bug. Probably should zero it in the start span probe only, and adjusting the convert attributes function to append to the attributes array instead of starting from index 0.

**Comment by asecondo** [comment]
fix for this was merged. closing issue.
