### ISSUE TITLE
Add log verbosity configuration and move the log in controller.go to debug level

### ISSUE THREAD

**Issue by RonFed** [open-telemetry/opentelemetry-go-instrumentation#691]
Currently, we print a log message for each span: 
https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/61ff124646105a2058863b17da1815d8d42d78b3/internal/pkg/opentelemetry/controller.go#L54

We should change that to have a debug level.
We don't have a configuration for verbosity. We probably should add support for configuration via:
1. command line arguments
2. `InstrumentationOption`
3. Enviroment variable (?)

This will need to be modified:
https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/61ff124646105a2058863b17da1815d8d42d78b3/instrumentation.go#L70-L83

**Comment by RonFed** [comment]
@MrAlias @pellared  I'd be happy to hear your thoughts on this.
* Can we add the logger as an Instrumentation option? I saw this comment about it:
https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/02686f0a149b13fec4da73b9d40233a372fbd13b/instrumentation.go#L90-L94
* The log line mentioned in my first comment is the one I worried about since we currently have huge amounts of logs, so adding a verbosity option seems helpful (using the debug level for tests and development).

**Comment by khushijain21** [comment]
@RonFed is this open for contribution?

**Comment by RonFed** [comment]
@khushijain21 Sure

**Comment by khushijain21** [comment]
@vitorhugoro1 yes, you can go ahead

**Comment by RonFed** [comment]
@vitorhugoro1 I think we need to support the first 2, and not sure about env var.
@MrAlias What do you think?

**Comment by pellared** [comment]
Regarding env var I think we should support `OTEL_LOG_LEVEL` per https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/configuration/sdk-environment-variables.md#general-sdk-configuration
