### ISSUE TITLE
Audit and update `database/sql` instrumentation to comply with SQL semantic conventions

### ISSUE THREAD

**Issue by damemi** [open-telemetry/opentelemetry-go-instrumentation#743]
https://github.com/open-telemetry/semantic-conventions/blob/a04a1f4ba413d0a1f137c223fc243ea14fdcd89b/docs/database/sql.md

**Comment by damemi** [comment]
Latest semconv: https://github.com/open-telemetry/semantic-conventions/blob/21b8f4620d2029fe8abb98a4a06655da3232d11d/docs/database/sql.md

Required attributes:
* `db.collection.name` (“if readily available. The collection name MAY be parsed from the query text, in which case it SHOULD be the first collection name found in the query.”)
* `db.namespace` (“if available”)
* `db.operation.name` (“if readily available. The operation name MAY be parsed from the query text, in which case it SHOULD be the first operation name found in the query.)
* `error.type` (“if and only if the operation failed”)
* `server.port` (If using a port other than the default port for this DBMS and if `server.address` is set.

Client calls semconv: https://github.com/open-telemetry/semantic-conventions/blob/21b8f4620d2029fe8abb98a4a06655da3232d11d/docs/database/database-spans.md

> ## Name
>
> Database spans MUST follow the overall [guidelines for span names](https://github.com/open-telemetry/opentelemetry-specification/tree/v1.33.0/specification/trace/api.md#span).
>
> The **span name** SHOULD be `{db.operation.name} {target}` if there is a
(low-cardinality) `{db.operation.name}` available (see below for the exact definition of the [`{target}`](#target-placeholder) placeholder).
>
> If there is no (low-cardinality) `db.operation.name` available, database span names
SHOULD be [`{target}`](#target-placeholder).
>
> If neither `{db.operation.name}` nor `{target}` are available, span name SHOULD be `{db.system}`.
>
> Semantic conventions for individual database systems MAY specify different span name format.
> 
> The <span id="target-placeholder">`{target}`</span> SHOULD describe the entity that the operation is performed against
and SHOULD adhere to one of the following values, provided they are accessible:
>
> - `db.collection.name` SHOULD be used for data manipulation operations or operations on database collections.
> - `db.namespace` SHOULD be used for operations on a specific database namespace.
> - `server.address:server.port` SHOULD be used for other operations not targeting any specific database(s) or collection(s)
>
>If a corresponding `{target}` value is not available for a specific operation, the instrumentation SHOULD omit the `{target}`.
>For example, for an operation describing SQL query on an anonymous table like `SELECT * FROM (SELECT * FROM table) t`, span name should be `SELECT`.

We currently [only set the span name to `DB`](https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/8c8fe6d8e28790267e9d2e7d5231c7b0396f233c/internal/pkg/instrumentation/bpf/database/sql/probe.go#L98).

Required attributes (not including common attributes from the previous section):

* `db.system`

# Updates:

- [ ] Set the appropriate span name
- [ ] Set `db.system`
- [ ] Set `[db.collection.name](http://db.collection.name/)`
- [ ] Set `db.namespace`
- [ ] Set `[db.operation.name](http://db.operation.name/)`
- [ ] Set `error.type`
- [ ] Set `server.port` / `server.address`

**Comment by damemi** [comment]
With #1253 we have db target and operations for basic operations, and we have the required attributes for client calls in https://github.com/open-telemetry/semantic-conventions/blob/21b8f4620d2029fe8abb98a4a06655da3232d11d/docs/database/database-spans.md

The only one we are missing is `error.type`. Looking at the query functions we probe though, the errors are returned as an interface that's specific to the SQL driver used (for example our sqlite example returns a [`go-sqlite3.Error`](https://pkg.go.dev/github.com/mattn/go-sqlite3#Error). This means we can't read a generic error for all queries. I was hoping that the  `database/sql` library would implement its own Error struct, which we could use, but that isn't the case.

So, it seems like error spans will have to be reported for individual driver instrumentations, like we were planning for `db.system` and other attributes. Based on that, I'm closing this as we have done the best possible for the standard db library.

**Comment by shaunak-10** [comment]
Hi, could you please clarify whether the current database/sql instrumentation emits the db.system attribute (for example, mysql, postgresql, etc.)?

I’m currently auto-instrumenting a Go application, but I’m not seeing the db.system attribute in the generated spans.
