### ISSUE TITLE
Fix offset generation cache

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-instrumentation#762]
> I noticed that if I rebuild the `offsetgen` tool, delete the entries from the json file, and run it for the first time it gets it right, and the second time it puts all these wrong values, so I'm guessing there is some bug in the cache mechanism there.

_Originally posted by @RonFed in https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/740#discussion_r1554640859_

**Comment by damemi** [comment]
+1 I'm also seeing weird behavior with the cache when trying to add fields in https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/790. Just running `make docker-offsets` caused the existing versions to get wiped and replaced with repeated `{}` entries. Deleting `.tools/` and `internal/pkg/inject/offset_results.json` then re-running the tool seems to work
