### ISSUE TITLE
Add feature gate for unstable/experimental libraries

### ISSUE THREAD

**Issue by damemi** [open-telemetry/opentelemetry-go-instrumentation#776]
Some of our instrumented libraries like `database/sql` and `kafka` currently rely on unstable semantic conventions. These should be put behind a feature gate that users have to explicitly enable in the agent for automatic instrumentation to pick up these libraries.

The reasoning for this is that users who expect automatic instrumentation may not be aware that the agent is using an experimental set of conventions for their library (due to the low investment of enabling automatic instrumentation).

So, when the conventions change, the users will be surprised by changes in their automatic instrumentation output. Putting this behind a feature gate draws their attention to the semantic conventions and makes them aware that this is likely to change.

**Comment by MrAlias** [comment]
Closing to consolidate the discussion in #785
