### ISSUE TITLE
context propagation does not work with http

### ISSUE THREAD

**Issue by JamieDanielson** [open-telemetry/opentelemetry-go-instrumentation#79]
### Describe the bug

Context propagation does not work with http; a new trace id is created each request instead of a distributed trace. 

### Environment

 - OS: kind/k8s 1.26 on mac/docker
 - Go Version: 1.20
 - Version: docker image built with latest commit [859307d](https://github.com/open-telemetry/opentelemetry-go-instrumentation/commit/859307debe421533dcf2e0192b5f89c021458e53) 

### To Reproduce

See [example app using this](https://github.com/honeycombio/example-greeting-service/tree/jamie.k8s-go-auto/go-auto-instrumented), where events show up but are not a distributed trace. I am using `OTEL_PROPAGATORS` with values of `"tracecontext,baggage"`.

![egs-separate-trace-ids](https://user-images.githubusercontent.com/29520003/232171230-2b1fd95c-0816-4a76-b9f4-268673dd505a.png)

### Expected behavior

The spans are connected in a distributed trace with the same trace id.

**Comment by MikeGoldsmith** [comment]
I'm looking into this now. It doesn't look like request headers are read in the `ServerMux_ServeHTTP` and written to outbound HTTP requests.

**Comment by vreynolds** [comment]
It looks like there were 2 open PRs that addressed this in the OG key-val repo:
https://github.com/keyval-dev/opentelemetry-go-instrumentation/pull/49/
and 
https://github.com/keyval-dev/opentelemetry-go-instrumentation/pull/50/

**Comment by mayanksingh2298** [comment]
Hey, any update on this? Are we integrating these MRs in this repo?

**Comment by MikeGoldsmith** [comment]
> Hey, any update on this? Are we integrating these MRs in this repo?

Hey @mayanksingh2298 - yes, @oxeye-gal ported their PRs over in #91 & #92. Once merged, propagation should be working.

**Comment by damemi** [comment]
Maybe relevant -- ? https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/220

**Comment by zengyuxing007** [comment]
You can try this mirror to see if it can solve your problem.

 vifoggy/otel-go-instrumentation:v0.2.2-alpha
