### ISSUE TITLE
Where can I downlowd the Go Automatic Instrumnentation binary  file

### ISSUE THREAD

**Issue by soulmate1314** [open-telemetry/opentelemetry-go-instrumentation#800]
### Describe the bug

Where can I get the Go Automatic Instrumnentation binary  file

### Compiling the project

Building requires Linux with kernel 4.4 or higher.
In addition, use the latest versions of the following components:

- `clang`
- `gcc`
- `go`
- `libbpf-dev`
- `llvm`
- `make`

Build the Go Automatic Instrumnentation binary by running:
`make build`

I tried to execute build on Centos7, but encountered the following error. I don't know which version of LLVM is needed.
So, I want a file that has already been compiled
“
go generate ./...
Error: exec: "llvm-strip": executable file not found in $PATH
exit status 1
internal/pkg/instrumentation/bpf/database/sql/probe.go:34: running "go": exit status 1
Error: exec: "llvm-strip": executable file not found in $PATH
exit status 1
internal/pkg/instrumentation/bpf/github.com/gin-gonic/gin/probe.go:34: running "go": exit status 1
Error: exec: "llvm-strip": executable file not found in $PATH
exit status 1
internal/pkg/instrumentation/bpf/go.opentelemetry.io/otel/traceglobal/probe.go:38: running "go": exit status 1
Error: exec: "llvm-strip": executable file not found in $PATH
exit status 1
internal/pkg/instrumentation/bpf/google.golang.org/grpc/client/probe.go:39: running "go": exit status 1
Error: exec: "llvm-strip": executable file not found in $PATH
exit status 1
internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/probe.go:37: running "go": exit status 1
Error: exec: "llvm-strip": executable file not found in $PATH
exit status 1
internal/pkg/instrumentation/bpf/net/http/client/probe.go:39: running "go": exit status 1
Error: exec: "llvm-strip": executable file not found in $PATH
exit status 1
internal/pkg/instrumentation/bpf/net/http/server/probe.go:36: running "go": exit status 1
make: *** [generate] Error 1
”

**Comment by damemi** [comment]
@soulmate1314 we don't currently publish a pre-compiled binary. We are planning to do this as part of https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/391. You can track support for this in that issue, closing this one as a duplicate. Thanks!
