### ISSUE TITLE
empty spans are generated by auto-instrumentation

### ISSUE THREAD

**Issue by JamieDanielson** [open-telemetry/opentelemetry-go-instrumentation#81]
>I think this empty span is a bug in the auto-instrumentation, but that should be a separate issue to track instead of fix in this PR
_Originally posted by @damemi in https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/46#discussion_r1155999231_

This was discussed during SIG meeting. The [traces.json output](https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/main/test/e2e/nethttp/traces.json#L65) being used for the e2e test shows the currently incorrect behavior of empty span IDs being generated with auto-instrumentation. This test should convert span IDs to "xxxxx" as seen in the top span, and the extra span appears to be a duplicate with no information.

I think I've traced this back to this PR #34 - specifically, keeping both function names for net/http instrumentation. If I adjust the code to only use `"net/http.HandlerFunc.ServeHTTP"` I don't have duplicated empty span IDs. Note I'm also working on some other changes that could also impact this so I might be off in the specific area causing this, but would be curious to try a test with this (the e2e tests were added after this change was made).

**Comment by damemi** [comment]
@JamieDanielson thanks for digging into this, if you have the change you think will fix it can you please open the PR? It would be interesting to see if the e2es catch the fix

**Comment by JamieDanielson** [comment]
Some changes from #86 have been ported over to #82, including the change to keep one function name for ServeHTTP... and this has solved the issue of empty spans. #86 has been updated to specifically add back the scoped spans for gorilla/mux.
