### ISSUE TITLE
add fixture-based e2e test for grpc instrumentation

### ISSUE THREAD

**Issue by JamieDanielson** [open-telemetry/opentelemetry-go-instrumentation#85]
**Is your feature request related to a problem? Please describe.**

As mentioned in #46 
> I added sample apps for gorillamux and net/http. If someone else wants to add a gRPC app, I think the first 2 serve as a good example. New libraries should be able to drop in similarly.

**Describe the solution you'd like**

A sample app for gRPC instrumentation with similar behavior to the gorillamux and nethttp example apps, with a test to verify output.

**Comment by MikeGoldsmith** [comment]
I'm working on this now.
