### ISSUE TITLE
Change `OTEL_TARGET_EXE` to `OTEL_GO_AUTO_TARGET_EXE`

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go-instrumentation#96]
Change `OTEL_TARGET_EXE` to `OTEL_GO_AUTO_TARGET_EXE` to follow https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/configuration/sdk-environment-variables.md#language-specific-environment-variables:

> To ensure consistent naming across projects, this specification recommends that language specific environment variables are formed using the following convention: `OTEL_{LANGUAGE}_{FEATURE}`

We adopt the same pattern in [OTel .NET Auto](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/config.md)

**Comment by pellared** [comment]
> LGTM, however I'm thinking whether `TARGET_EXE` is best name for this variable

@pdelewski  Feel free to propose a better name. For me it is good and clear enough.

**Comment by MikeGoldsmith** [comment]
I agree with @pellared. I think `TARGET_EXE` is clear enough.
